Task 2.6 (Реворк экрана профиля)
iOS-vk-education/2022_1s_OnWheels pull request #11
Opened 2023-03-24 12:42 UTC by ArtemTin

2023-03-25 12:04 UTC, Grandschtien requested changes

2023-03-25 12:04 UTC, Grandschtien commented on OnWheels.xcodeproj/project.pbxproj
> +				DEVELOPMENT_TEAM = "";
Это лучше не комитить, чтобы лишних конфликтов не было

2023-03-25 12:04 UTC, Grandschtien commented on OnWheels/Enter/EnterViewController.swift
> +        UIView.animate(withDuration: timeInterval) {
Не долгая анимация будет?

2023-03-25 12:04 UTC, Grandschtien commented on OnWheels/Profile/Cell/ProfileInfoCell.swift
> +        nil
лучше return оставь, читается лучше

2023-03-25 12:04 UTC, Grandschtien commented on OnWheels/Profile/Cell/ProfileInfoCell.swift
> +            let formatter1 = DateFormatter()
Это надо вынести из ячейки, лучше передай уже готовую строку туда

2023-03-25 12:04 UTC, Grandschtien commented on OnWheels/Profile/ProfileRouter.swift
> +        // call to networking...
Вот тут лучше не вызывать ничего, сам вызов пусть делает interactor

2023-03-25 12:04 UTC, Grandschtien commented on OnWheels/Profile/Cell/ProfileInfoCell.swift
> +                formatter2.dateFormat = "d MMMM yyyy"
Тут кстати еще можно паттерн "стратегия" применить, могу кинуть пример если хочешь

2023-03-25 12:04 UTC, Grandschtien commented on OnWheels/Profile/Cell/ProfileInfoCell.swift
> +                formatter2.dateFormat = "d MMMM yyyy"
Чтоб стрингами так не писать форматтеры посреди кода

2023-03-25 21:37 UTC, ArtemTin commented on OnWheels/Enter/EnterViewController.swift
> +        UIView.animate(withDuration: timeInterval) {
Секунда? Вроде ок. Задержка специально сделана

2023-03-25 21:48 UTC, ArtemTin commented on OnWheels/Profile/ProfileRouter.swift
> +        // call to networking...
Вот это не понял

2023-03-25 21:49 UTC, ArtemTin commented on OnWheels/Profile/Cell/ProfileInfoCell.swift
> +                formatter2.dateFormat = "d MMMM yyyy"
А не легче просто в R.swift эти две строчки добавить?

2023-03-25 21:51 UTC, ArtemTin commented on OnWheels.xcodeproj/project.pbxproj
> +				DEVELOPMENT_TEAM = "";
Не знаю, как это отревертить так, чтобы остальная часть файла не сломалась
Грустно, что так получилось

2023-03-30 08:05 UTC, Grandschtien commented on OnWheels.xcodeproj/project.pbxproj
> +				DEVELOPMENT_TEAM = "";
сделай черри пик с нудными изменениями или отревевши конкретную строку

2023-03-30 08:05 UTC, Grandschtien commented on OnWheels/Enter/EnterViewController.swift
> +        UIView.animate(withDuration: timeInterval) {
Ну смотрите сами, если норм смотрится, то ок

2023-03-30 08:06 UTC, Grandschtien commented on OnWheels/Profile/ProfileRouter.swift
> +        // call to networking...
Это я на будущие) У тебя прост комент в роутере о вызове сети, сеть должна работать только из интерактора

2023-03-30 08:07 UTC, Grandschtien commented on OnWheels/Profile/Cell/ProfileInfoCell.swift
> +                formatter2.dateFormat = "d MMMM yyyy"
Это не локализация, а форматы даты, это лучше сделать как отдельный объект или группа объектов(стратегия) и только нужно вытаскивать их ячейки

2023-03-30 08:15 UTC, Grandschtien commented on OnWheels/Profile/Cell/ProfileInfoCell.swift
> +                formatter2.dateFormat = "d MMMM yyyy"
Ваще я посоветовал стратегию, так как она избавит тебя от кучи if в коде, очень удобная штука. Но это задание со звездочкой так сказать, если не захочется, можешь просто вынести это в некий объект и передавать в аргументы функции к примеру этот форматтер. Ну или расширение для Date

2023-04-01 22:27 UTC, ArtemTin commented on OnWheels/Profile/ProfileRouter.swift
> +        // call to networking...
> Это я на будущие) У тебя прост комент в роутере о вызове сети, сеть должна работать только из интерактора

то есть надо в презентере дергать interactor.deleteAccount() ?

2023-04-02 10:00 UTC, ArtemTin commented on OnWheels/Profile/Cell/ProfileInfoCell.swift
> +                formatter2.dateFormat = "d MMMM yyyy"
Вроде сделал

2023-04-03 09:37 UTC, Grandschtien commented on OnWheels/Profile/ProfileViewController.swift
>      private var user: CurrentUser?
Давай в контролере не будем хранить инфу никакую, это по сути вьюха, передай сюда info и пусть он ее просто отобразит. Если хочешь хранить инфу юзера перекинь ее в UserDefaults(не надежно, но можно) или в KeyChain(рекомендовано)

2023-04-03 09:37 UTC, Grandschtien commented on OnWheels/Profile/ProfileViewController.swift
>      private var user: CurrentUser?
Вообще в целом давай логику экрана переделаем, у нас зачем то тут таблица(что большой оверхед для такого экрана). Сделай вьюху отдельную и передавай туда модель(не храни ее в целом в классах, храни где нибудь в кейчейне или юзердефалтсах). На первый взгляд уйдет почти 150 строчек примерно если убрать таблицу из экрана)

2023-04-03 09:37 UTC, Grandschtien commented on OnWheels/Profile/ProfileViewController.swift
>      private var user: CurrentUser?
+ насколько я понимаю ты занимаешься чисто профилем, поэтому давай еще приделаем сюда менеджер акаунта, который будет чисто работать с Акком и менеджер токенов, который будет чисто с токенов работать

2023-04-19 05:08 UTC, Grandschtien requested changes
В дополнение проверь схожесть с дизайном плз

2023-04-19 05:08 UTC, Grandschtien commented on Localization/en.lproj/Localizable.strings
> +"logout" = "logout";
Наверное с большой буквы

2023-04-19 05:08 UTC, Grandschtien commented on OnWheels/Helpers/Coordinator/MainFlowCoordinator.swift
> +        navController.setViewControllers([profileContainer.view as UIViewController], animated: true)
давай не будем кастить. Лучше в profileBuilder был UIViewController

2023-04-19 05:08 UTC, Grandschtien commented on OnWheels/Profile/ProfileView/ProfileContentView.swift
> +
Поправь отступы везде, между функциями 1 enter

2023-04-19 05:08 UTC, Grandschtien commented on OnWheels/Profile/ProfileView/ProfileContentView.swift
> +        }
тут тоже отступы

2023-04-19 05:08 UTC, Grandschtien commented on OnWheels/Profile/ProfileView/ProfileContentView.swift
> +        profileDetails.addArrangedSubviews(sexDescriptionLabel, sexLabel)
а зачем ты пересоздаешь все вьюхи, просто проставляй туда данные и все

2023-04-24 05:27 UTC, Grandschtien commented on OnWheels/Profile/ProfilePresenter/ProfilePresenterImpl.swift
> +                    let userInfo: ProfileUserInfo = ProfileUserInfo(name: user.firstname + " " + user.lastname, city: user.city, email: user.email, birthday: user.birthday, sex: user.sex)
Тут можно сделать два поля name и surname, а внутри модельки сделать вычисляемое свойство fullName, где будешь возвращать `user.firstname + " " + user.lastname`

2023-04-24 05:51 UTC, Grandschtien approved these changes

2023-04-24 05:51 UTC, merged