Экран профиля на MVP
iOS-vk-education/2022_1s_OnWheels pull request #12
Opened 2023-04-03 21:02 UTC by ArtemTin

2023-04-06 19:11 UTC, Grandschtien requested changes

2023-04-06 19:11 UTC, Grandschtien commented on OnWheels/Helpers/BaseComponents/Buttons.swift
> +func basicButtonConf(button: UIButton) -> UIButton.Configuration {
Давай вынесем это в расширение кнопки или в какой нибудь класс, глобальные функции не круто)

2023-04-06 19:11 UTC, Grandschtien commented on OnWheels/Profile/ProfilePresenter.swift
> +class ProfilePresenterImpl: ProfilePresenter {
Давай с неймингом слегка поработаем: 
1) Поменяй название файла, у нас тут ProfilePresenterImpl, а не ProfilePresenter
2)  Давай не будем сокращать (vc - viewController)
3) Давай в init сделаем userNetworkManager (название аргумента)
4) ProfileViewControllerProtocol - не оч подходящие, дава как нибудь ProfileView, а саму вьюху назовем ProfileContentView
5) КОменты не оставляй лучше, они код загрязняют, а инфы не несут по сути (за исключением TODO и MARK)

2023-04-06 19:11 UTC, Grandschtien commented on OnWheels/Profile/ProfileProtocols.swift
> +protocol ProfilePresenter {
Вот тут для каждого протокола отдельный файл, причем лучше объединять в папки по типу:
папка: ProfilePresenter
      - Протокол: ProfilePresenter
      - Класс: ProfilePresenterImpl

2023-04-06 19:11 UTC, Grandschtien commented on OnWheels/Profile/ProfileRouter.swift
> +class ProfileRouterImpl: ProfileRouter {
Опять же название файла и класса + пробегись по классам и те, что не имеют дочерних классов final сделай

2023-04-06 19:11 UTC, Grandschtien commented on OnWheels/Profile/ProfileRouter.swift
> +    required init(window: UIWindow, navigationController: UINavigationController) {
В целом init не обязательно в протокол выносить(это опционально)

2023-04-06 19:11 UTC, Grandschtien commented on OnWheels/Profile/ProfileRouter.swift
> +    func setVC(vc: UIViewController) {
ViewController

2023-04-06 19:11 UTC, Grandschtien commented on OnWheels/Profile/ProfileRouter.swift
> +            navigationController.pushViewController(viewController, animated: true)
Вот тут не понял смысл, что эта функция должна делать?

2023-04-06 19:11 UTC, Grandschtien commented on OnWheels/Profile/ProfileView.swift
> +typealias ProfileLogoutAction = () -> Void
Давай внесем в класс этот typealias

2023-04-06 19:11 UTC, Grandschtien commented on OnWheels/Profile/ProfileView.swift
> +    private let userAvatar = UIImageView(frame: .zero)
тут frame не обязательно прописывать

2023-04-06 19:11 UTC, Grandschtien commented on OnWheels/Profile/ProfileView.swift
> +        [userAvatar, userNameLabel, userCityLabel, profileDetails, deleteAccountButton, logoutButton].forEach {
давай это вынесем в отдельную функцию

2023-04-06 19:11 UTC, Grandschtien commented on OnWheels/Profile/ProfileView.swift
> +    func profileLogoutButtonConf() {
Давай лучше setupProfileLogoutButton

2023-04-06 19:11 UTC, Grandschtien commented on OnWheels/Profile/ProfileView.swift
> +    func profileDeleteButtonConf() {
setupProfileDeleteButton

2023-04-06 19:11 UTC, Grandschtien commented on OnWheels/Profile/ProfileViewController.swift
> +    private var prView = ProfileView(frame: .zero)
private lazy var profileView = ProfileView()

2023-04-06 19:11 UTC, Grandschtien commented on OnWheels/Profile/ProfileViewController.swift
> +        self.presenter.setVC(vc: self)
Это в билдер сетей

2023-04-06 19:11 UTC, Grandschtien commented on OnWheels/Profile/ProfileViewController.swift
> +        self.presenter.update()
Это вызывай во viewDidAppear

2023-04-06 19:11 UTC, Grandschtien commented on OnWheels/Profile/ProfileViewController.swift
> +//// MARK: - keyboard hiding
Давай уберем

2023-04-06 19:11 UTC, Grandschtien commented on OnWheels/Profile/ProfileViewController.swift
> +        self.presenter.setVC(vc: self)
Ща увидел, у тебя уже сетается контроллер в презентер в билдере

2023-04-07 20:25 UTC, ArtemTin commented on OnWheels/Profile/ProfilePresenter.swift
> +class ProfilePresenterImpl: ProfilePresenter {
Вроде сделал, проверь плиз

2023-04-09 11:08 UTC, Grandschtien requested changes
Все ок(ток один момент с роутером), только давай пробежимся по модулю, уберем все коменты и расставим TODO(их проще в поиске искать) и поправим отступы, все должно идти через одну строку(кроме хранимых полей, их можно стакать)

2023-04-09 11:08 UTC, Grandschtien commented on OnWheels/Profile/ProfileBuilder.swift
> +        let router = ProfileRouterImpl(window: window, navigationController: navigationController)
а давай не будем передавать в аргументы navigationController, ты можешь достучаться до него в самом роутере через поля UIViewController

2023-04-10 08:25 UTC, Grandschtien approved these changes
На будущее: Следите за отступами, чтобы не было вразнобой

2023-04-10 08:25 UTC, merged