Nika/task2 3
iOS-vk-education/2022_1s_OnWheels pull request #13
Opened 2023-04-08 09:40 UTC by nika-rvv

Сделала верстку экрана добавления гонки

2023-04-09 11:24 UTC, Grandschtien requested changes
Все в целом норм, коменты в основном на дизайн кода. Прочекай отступы тоже что ниче не уезжало

2023-04-09 11:24 UTC, Grandschtien commented on Localization/en.lproj/Localizable.strings
> +"alertMessage" = "Check fields completion";
Договоритесь о том, как вы локализацию юзаете (у Артема прост через нижнее подчеркивание название строк)

2023-04-09 11:24 UTC, Grandschtien commented on OnWheels/AddEvent/AddEventContainer.swift
> +final class AddEventContainer {
Вот тут че то прям сильно отступы поехали))

2023-04-09 11:24 UTC, Grandschtien commented on OnWheels/AddEvent/AddEventContainer.swift
> +	class func assemble(with context: AddEventContext) -> AddEventContainer {
Эта функция будет перегружена где то?

2023-04-09 11:24 UTC, Grandschtien commented on OnWheels/Helpers/AddEventContentView.swift
> +        description.layer.cornerRadius = 4
два раза `description.layer.cornerRadius = 4`

2023-04-09 11:24 UTC, Grandschtien commented on OnWheels/Helpers/AddEventContentView.swift
> +        addVeiws()
очепятка

2023-04-09 11:24 UTC, Grandschtien commented on OnWheels/Helpers/AddEventContentView.swift
> +        fatalError("init(coder:) has not been implemented")
return nil

2023-04-09 11:24 UTC, Grandschtien commented on OnWheels/Helpers/AddEventContentView.swift
> +                               for: UIControl.Event.valueChanged)
Тут не обязательно фуд писать `UIControl.Event.valueChanged` можно прост `.valueChanged`

2023-04-09 11:24 UTC, Grandschtien commented on OnWheels/Helpers/AddEventContentView.swift
> +extension AddEventContentView {
Давай разобьем это расширение на несколько, очень трудно читать из-за того, что много методов. Можно например все actionHandlerы вынести в отдельно (если их много можно также поделить на несколько) + сделать `private extension` для функций настраивающих UI

2023-04-09 11:24 UTC, Grandschtien commented on OnWheels/Helpers/AddEventContentView.swift
> +    func formatDate(date: Date) -> String {
Такие штуки в вьюхе лучше не делать, всякие валидации в перезнтере

2023-04-09 11:24 UTC, Grandschtien commented on OnWheels/Helpers/AddEventContentView.swift
> +        if textView.textColor == R.color.textFieldText() {
Давай всю логику из вью уберем в презентер

2023-04-09 11:27 UTC, nika-rvv commented on Localization/en.lproj/Localizable.strings
> +"alertMessage" = "Check fields completion";
ну у меня там все строки сделаны без нижнего подчеркивания, поэтому считаю логичным оставить так, чтобы не исправлять все

2023-04-10 10:59 UTC, Grandschtien requested changes
В основном косметические моменты, а так все ок

2023-04-10 10:59 UTC, Grandschtien commented on Networking/EndPoint/RaceEndPoint.swift
> +        case .postRace(raceInfo: _):
Тут можно не писать аргументы

2023-04-10 10:59 UTC, Grandschtien commented on OnWheels/AddEvent/AddEventInteractor.swift
> +                                           images: [""],
Если не юзается давай уберем, код чтоб почище был

2023-04-10 10:59 UTC, Grandschtien commented on OnWheels/AddEvent/AddEventProtocols.swift
> +	var moduleOutput: AddEventModuleOutput? { get }
Поихало

2023-04-10 10:59 UTC, Grandschtien commented on OnWheels/Entities/RacesModel.swift
> +    let date: DateClass
А что за DateClass?

2023-04-10 10:59 UTC, Grandschtien commented on OnWheels/Entities/RacesModel.swift
> +    let date: DateClass
Увидел, давай сделает Duration, не ясно что за DateClass и за что отвечает

2023-04-10 10:59 UTC, Grandschtien commented on OnWheels/Helpers/CustomMainButton.swift
> +class CustomButton: UIButton {
Давай сделаем BaseButton(вместо CustomButton) и почистим иниты, а то много как то написано

2023-04-10 10:59 UTC, Grandschtien commented on OnWheels/Helpers/CustomMainButton.swift
> +class CustomButton: UIButton {
Задание со звездочкой* 
- Почитай про абстрактную фабрику или обычную фабрику и попробуй сюда применить

2023-04-10 10:59 UTC, Grandschtien commented on OnWheels/Helpers/LocationDecoder.swift
> +            let location = Location(latitude: placemark.location?.coordinate.latitude ?? 0, longitude: placemark.location?.coordinate.longitude ?? 0)
Такие строки лучше разбивать, читать трудно

2023-04-10 10:59 UTC, Grandschtien commented on OnWheels/LogIn/LogInViewController.swift
> +        let button = CustomButton()
просто в строчку лучше пиши сразу, тут замыкание лишнее

2023-05-21 18:29 UTC, Grandschtien requested changes

2023-05-21 18:29 UTC, Grandschtien commented on OnWheels/AddEvent/AddEventViewController.swift
> +    private let labels = ["название", "дата начала",
А че локализацию не заюзала

2023-05-21 18:29 UTC, Grandschtien commented on OnWheels/Helpers/AddEventContentView.swift
> +        if textView.textColor == R.color.textFieldText() {
тут тоже)

2023-05-22 15:14 UTC, nika-rvv commented on OnWheels/Helpers/AddEventContentView.swift
> +        if textView.textColor == R.color.textFieldText() {
тут же просто цвет меняется у текста, когда пользователь начинает писать, думаю, нет смысла прокидывать в контроллер, потом в презентер и обратно) слишком много кода на цвет текста в текствью

2023-05-22 19:27 UTC, Grandschtien approved these changes

2023-05-22 19:27 UTC, merged