Andrey/task5
iOS-vk-education/2022_1s_OnWheels pull request #3
Opened 2022-11-17 18:46 UTC by strandmoscow

I've added events screen and myEvents screen.

2022-11-18 05:09 UTC, timoninas requested changes

2022-11-18 05:09 UTC, timoninas commented on OnWheels/Events/Cell/EventsInfoCell.swift
> +        return image!
Давай мб без force unwrap. Если не получилось достать изображение, значит пустое показываем

В рабочих проектах обычно табу на восклицательный знак. Лучше делать опционалом)

2022-11-18 05:09 UTC, timoninas commented on OnWheels/Events/Cell/EventsInfoCell.swift
> +        return image!
В местах ниже тоже самое

2022-11-18 05:09 UTC, timoninas commented on OnWheels/Events/Cell/EventsInfoCell.swift
> +    private let sharedImageView: UIImageView = {
Почему тут короче не создать?)

```Swift
private let sharedImageView = UIImageView()
```

2022-11-18 05:09 UTC, timoninas commented on OnWheels/Events/Cell/EventsInfoCell.swift
> +
Зачем нам эти пустые строчки?

2022-11-18 05:09 UTC, timoninas commented on OnWheels/Events/Cell/EventsInfoCell.swift
> +
Одной пустой строчки будет вполне достаточно, чтобы создавалось хоть какое-то визуальной пространство между пропертями

2022-11-18 05:09 UTC, timoninas commented on OnWheels/Events/Cell/EventsInfoCell.swift
> +    func configure(mainText: String, dateText: String, placeText: String, imageName: String, likeText: String, sharedText: String, watchedText: String) {
Длинная строка получилась. Давай перенесем каждый параметр на новую строчку

2022-11-18 05:09 UTC, timoninas commented on OnWheels/Events/EventsViewController.swift
> +        return 3
Можно без `return`

2022-11-18 05:09 UTC, timoninas commented on OnWheels/Events/EventsViewController.swift
> +        eventsTableView.separatorStyle = .none
На будущее. По сути с выходом `collectionView`, `tableView` перешло в разряды deprecated. Тк коллкшн вью более гибкая, туда можно сой лейаут написать и тд. Советовал бы все, что делаешь и где нужны ячейки испоользовать `collectionView`. Тут необязательно это переделывать. Но так, совет на будущее

2022-11-18 05:09 UTC, timoninas commented on OnWheels/Events/EventsViewController.swift
> +            cell.configure(mainText: "Чемпионат России", dateText: "7 янв. - 10 янв.", placeText: "Респ. Башкортостан, Уфа", imageName: "durtbike", likeText: "20", sharedText: "20", watchedText: "20"
Мб данные из viewModel брать, которая будет через презентер прокидываться?

2022-11-18 05:09 UTC, timoninas commented on OnWheels/Events/EventsViewController.swift
> +        return UIScreen.main.bounds.height / 2
Почему тут не взять размер tableView, который передан тебе в этот метод?

2022-11-18 05:09 UTC, timoninas commented on OnWheels/MyEvents/MyEventsContainer.swift
> +        let router = MyEventsRouter()
Тут, кажется, форматирование поехало. Попробуй авто форматнуть клавишами: `cntrl + i`

2022-11-18 05:09 UTC, timoninas commented on OnWheels/MyEvents/MyEventsPresenter.swift
> +	weak var view: MyEventsViewInput?
Тоже форматирование поехало

2022-11-18 05:09 UTC, timoninas commented on OnWheels/MyEvents/MyEventsViewController.swift
> +            cell.configure(mainText: "Чемпионат России", dateText: "7 янв. - 10 янв.", placeText: "Респ. Башкортостан, Уфа", imageName: "durtbike", likeText: "20", sharedText: "20", watchedText: "20"
Кажется, я это уже где-то видел :)

2022-11-21 14:25 UTC, strandmoscow commented on OnWheels/Events/EventsViewController.swift
> +        eventsTableView.separatorStyle = .none
Окей, спасибо)

2022-11-21 14:26 UTC, strandmoscow commented on OnWheels/Events/EventsViewController.swift
> +            cell.configure(mainText: "Чемпионат России", dateText: "7 янв. - 10 янв.", placeText: "Респ. Башкортостан, Уфа", imageName: "durtbike", likeText: "20", sharedText: "20", watchedText: "20"
Ну это Ника сделает, когда с бэром будет развлекаться

2022-11-21 14:27 UTC, strandmoscow commented on OnWheels/Events/EventsViewController.swift
> +            cell.configure(mainText: "Чемпионат России", dateText: "7 янв. - 10 янв.", placeText: "Респ. Башкортостан, Уфа", imageName: "durtbike", likeText: "20", sharedText: "20", watchedText: "20"
к*

2022-12-05 05:57 UTC, merged