Nika/task5 bugfix
iOS-vk-education/2022_1s_OnWheels pull request #7
Opened 2022-11-30 17:46 UTC by nika-rvv

Доделала навигацию в таблице и с экраном одного мероприятия, исправила навигейшн бар на логине, регистрации и мероприятиях, изменила кнопку назад, добавила немного анимации при нажатии кнопок, сделала переход с экрана одного мероприятия по скайпу

2022-12-04 05:24 UTC, timoninas requested changes

2022-12-04 05:24 UTC, timoninas commented on OnWheels/Events/Cell/EventsInfoCell.swift
> +    let likeInfoStackVeiw = EventInfoStackView()
Тут переменная не должна быть `private`  ?

В случае если все так и должно быть, то советую группировать переменные по public, internal, private и тд

2022-12-04 05:24 UTC, timoninas commented on OnWheels/Events/Cell/EventsInfoCell.swift
> +    override init(style: UITableViewCell.CellStyle, reuseIdentifier: String?) {
Не вижу никакого метода на случай реюза ячеек.

`prepareForReuse`. Ты когда ячейки скроллишь, новые ячейки которые появляются - они переиспользуются от старых. И прежде чем в новые ячейки вставить новые данные их нужно подготовить к реюзю. Давай добавим метод реюза, где будут очищаться данные и лейблов, кнопок и тд

2022-12-04 05:24 UTC, timoninas commented on OnWheels/Events/Cell/EventsInfoCell.swift
> +//        likeInfoStackVeiw.resignFirstResponder()
Комент убираем

2022-12-04 05:24 UTC, timoninas commented on OnWheels/Events/Cell/EventsInfoCell.swift
> +        likeInfoStackVeiw.isUserInteractionEnabled = true
Разве по дефолту не `true` ?

2022-12-04 05:24 UTC, timoninas commented on OnWheels/Events/Cell/EventsInfoCell.swift
> +            print("+1")
Принты тоже не нужны

2022-12-04 05:24 UTC, timoninas commented on OnWheels/Events/Cell/EventsInfoCell.swift
> +        if isEventLiked == false {
А почему так не хочешь смотреть проверку на `false`

```Swift
if !isEventLiked {
    ...
}
```

2022-12-04 05:24 UTC, timoninas commented on OnWheels/Events/Cell/EventsInfoCell.swift
> +    ///   - placeText: Место проведения
Не хватает доку для параметра `imageName`

2022-12-04 05:24 UTC, timoninas commented on OnWheels/Events/Cell/EventsInfoCell.swift
> +        if isLiked == true {
Просто `if isLiked {`

2022-12-04 05:24 UTC, timoninas commented on OnWheels/Events/EventsContainer.swift
> +	weak var moduleOutput: EventsModuleOutput?
Отступы поехали

2022-12-04 05:24 UTC, timoninas commented on OnWheels/Events/EventsViewController.swift
> +        return 10
Можно без `return`

2022-12-04 05:24 UTC, timoninas commented on OnWheels/Events/EventsViewController.swift
> +    internal func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
По дефолту итак будет `internal`. Так что можно этот модификатор убрать

2022-12-04 05:24 UTC, timoninas commented on OnWheels/MyEvents/MyEventsPresenter.swift
> +    weak var moduleOutput: MyEventsModuleOutput?
Тоже отступы поехали

2022-12-04 05:24 UTC, timoninas commented on Podfile.lock
> +  - PinLayout (1.10.3)
Тут аккуратнее. Если у вас вдруг версия поменяется и ваш код не будет готов к таком, то проект может поломаться. Так что советую четко фиксировать remote версии external пакетов

2022-12-04 17:13 UTC, nika-rvv commented on OnWheels/Events/EventsViewController.swift
> +        return 10
так просто понятнее мне

2022-12-05 05:28 UTC, timoninas approved these changes

2022-12-05 05:28 UTC, timoninas commented on OnWheels/Events/Cell/EventsInfoCell.swift
> +    ///   - placeText: Место проведения
Параметры в доке должны идти в том же порядке что и в инициализаторе

2022-12-05 05:57 UTC, merged